#!/bin/bash
export REMOTE=cybertruck.local
export REMOTE_DIR=$(ssh cybertruck.local "mktemp -d")

[[ -z "$REMOTE_DIR" ]] && { echo "REMOTE_DIR is empty"; exit 1; }

rsync -az --info=progress2 --exclude='.git' --exclude='.build*' ./ $REMOTE:$REMOTE_DIR
ssh $REMOTE "cd $REMOTE_DIR && pwd && ./pre-push $@ && rm -rf $REMOTE_DIR"
