[#install]

= Installation

:idprefix: install_

Before using the library, you can try it [online](https://godbolt.org/z/dvacqK8jE).

_Multi_ has no external dependencies and can be used immediately after downloading.
```bash
git clone https://gitlab.com/correaa/boost-multi.git
```

_Multi_ doesn't require installation since a single header `#include <multi/array.hpp>` is enough to use the entire core library;
still, the library can be installed with CMake.
The header (and CMake) files will be installed in the chosen prefix location (by default, `/usr/local/include/multi` and `/usr/local/share/multi`).
```bash
cd boost-multi
mkdir -p build && cd build
cmake ..  # --install-prefix=$HOME/.local
cmake --install .  # or sudo ...
```

_Testing_ the library requires Boost.Core (headers), installed for example, via `sudo apt install cmake git g++ libboost-test-dev make` or `sudo dnf install boost-devel cmake gcc-c++ git`.
A CMake build system is provided to compile and run basic tests.
```bash
cmake --build .
ctest
```

Once installed, other CMake projects (targets) can depend on Multi by adding a simple `add_subdirectory(my_multi_path)` or by `find_package`:
```cmake
find_package(multi)  # see https://gitlab.com/correaa/boost-multi
```

As an alternatively to using `find_package`, the library can be fetched on demand:
```cmake
include(FetchContent)
FetchContent_Declare(multi GIT_REPOSITORY https://gitlab.com/correaa/boost-multi.git)
FetchContent_MakeAvailable(multi)
...
target_link_libraries(my_target PUBLIC multi)
```

The code requires any C++ [compiler](https://godbolt.org/z/hxEYGYEWc) (or CUDA [compiler](https://godbolt.org/z/79Tqedhfs)) with standard C++17 support;
for reference, any of:
LLVM's       `clang` [(5.0+)](https://godbolt.org/z/51E1hjfnn) (`libc++` and `libstdc++`),
GNU's        `g++` [(7.1+)](https://godbolt.org/z/1nGEbKc5a),
Nvidia's    [`nvcc`](https://godbolt.org/z/abdT73PqM) (11.4+) 
and 
            [`nvc++`](https://godbolt.org/z/6z39PjT47) (22.7+),
Intel's      `icpx` (2022.0.0+) and `icc` (2021.1.2+, deprecated),
Baxter's    [`circle`](https://www.circle-lang.org/) ([build 202+](https://godbolt.org/z/KeG417fMz)),
[Zig](https://zig.news/kristoff/compile-a-c-c-project-with-zig-368j) in [c++ mode (v0.9.0+)](https://godbolt.org/z/cKGebsWMG),
Edison Desing's [EDG]() [(6.5+)](https://godbolt.org/z/693fxPedx)
and
Microsoft's [MSVC](https://visualstudio.microsoft.com/vs/features/cplusplus/) ([+14.1](https://godbolt.org/z/Kqrva137M)).

(Multi code inside CUDA kernel can be compiled with `nvcc` and with [`clang` (in CUDA mode)](https://godbolt.org/z/7dTKdPTxc).
Inside HIP code, it can be compiled with AMD's clang rocm (5.0+).)

Optional _adaptor_ sublibraries (included in `multi/adaptors/`) have specific dependencies: fftw, , lapack, thurst, or CUDA
(all of them can be installed with `sudo apt install libfftw3-dev lib64-dev liblapack64-dev libthrust-dev nvidia-cuda-dev` or `sudo dnf install -devel fftw-devel ...`.)

In the following sections we present basic and advanced uses of the libraries. 
Feel free to jump to the "Reference of fundamental types" section to explore a more exhaustive description of the classes provided by the library.
